import { Button, VerticalBox , HorizontalBox, ComboBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> modpack;
    in property<float> scale;
    in property <bool> components_enabled: true;
    in property <[string]> modpacks;
    title: "Minecraft Modpack Manage Lite";
    default-font-size: 24px * scale;
    preferred-width: 640px * scale;
    preferred-height: 480px * scale;
    icon: @image-url("images/logo.png");
    min-width: 640px;
    max-height: 480px;

    // background: #1e293b;
    callback apply();
    callback clear();
    callback reload();
    callback select_modpack(string);

    VerticalLayout {
        alignment: center;
        Image {
            source: @image-url("images/logo.svg");
            min-height: 64px;
            min-width: 64px;
            preferred-height: 64px * scale;
            preferred-width: 64px * scale;
        }
        HorizontalBox {
            alignment: center;
            ComboBox {
                width: 320px * scale;
                height: 48px * scale;
                enabled: components-enabled;
                model: modpacks;
                current-value: modpack;
                selected(value) => {
                    select-modpack(value);
                }
            }
        }
        HorizontalBox {
            // alignment: center;
            Button {
                height: 24px * scale;
                // width: 36px * scale;
                text: "Apply";
                clicked => {
                    root.apply();
                }
                enabled: components-enabled;
            }
            Button {
                height: 24px * scale;
                // width: 36px * scale;
                text: "Clear";
                clicked => {
                    root.clear();
                }
                enabled: components-enabled;
            }
            Button {
                height: 24px * scale;
                // width: 36px * scale;
                text: "Reload";
                clicked => {
                    root.reload();
                }
                enabled: components-enabled;
            }
         }
    }
}
